# Generated by Django 5.1.3 on 2024-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance_from_me', models.DecimalField(decimal_places=2, help_text='Distance in miles', max_digits=5)),
                ('cost_range', models.CharField(choices=[('$', 'Budget'), ('$$', 'Moderate'), ('$$$', 'Expensive')], max_length=3)),
            ],
        ),
    ]
