# Generated by Django 5.1.3 on 2024-11-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='distance_from_me',
            field=models.DecimalField(decimal_places=2, help_text='Distance in minutes', max_digits=5),
        ),
    ]
