# Generated by Django 5.1.2 on 2024-10-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_statusmessageimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusmessageimage',
            old_name='image',
            new_name='image_file',
        ),
    ]
